version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: anything
      MYSQL_DATABASE: lacakio_challange
      MYSQL_USER: lacakiouser
      MYSQL_PASSWORD: lacakiopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring-boot-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/lacakio_challange
      SPRING_DATASOURCE_USERNAME: lacakiouser
      SPRING_DATASOURCE_PASSWORD: lacakiopassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "80:8080"

volumes:
  mysql_data:
